Update README.md
ChainSafe/bls-js pull request #31
Opened 2019-05-25 22:00 UTC by GregTheGreek

2019-05-26 02:23 UTC, mpetrunic requested changes

2019-05-26 02:23 UTC, mpetrunic commented on README.md
> +- `npm install @chainsafe/bls-js --save`
you should update yarn alternative below also

2019-05-27 17:59 UTC, mpetrunic approved these changes

2019-05-28 13:19 UTC, wemeetagain approved these changes

2019-05-28 13:19 UTC, merged